ARG version
FROM almalinux:-$version
ENV Name="Satya vardhan" \
    Age="23"
ARG weight="12"
RUN echo "Hello world ... my name is ${Name} and age is ${Age} and height is ${weight} and version ${version}" > hello.txt
