FROM almalinux:9

# Install Nginx
RUN dnf install nginx -y

# Remove default index.html
RUN rm -rf /usr/share/nginx/html/index.html

# Add new file from GitHub
ADD https://raw.githubusercontent.com/daws-84s/notes/refs/heads/main/session-01.txt /usr/share/nginx/html/index.html

# Run nginx in foreground when container starts
CMD ["nginx", "-g", "daemon off;"]
